spring:
  datasource:
    url: jdbc:mysql:///paascloud_tpc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-tpc
      consumerGroup: CID_TPC
      producerGroup: PID_TPC
